// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: plc_ide_nrt_v1.proto
#ifndef GRPC_plc_5fide_5fnrt_5fv1_2eproto__INCLUDED
#define GRPC_plc_5fide_5fnrt_5fv1_2eproto__INCLUDED

#include "plc_ide_nrt_v1.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace plcide {

class PLCRuntimeService final {
 public:
  static constexpr char const* service_full_name() {
    return "plcide.PLCRuntimeService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderInterface< ::plcide::LogEntry>> ExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request) {
      return std::unique_ptr< ::grpc::ClientReaderInterface< ::plcide::LogEntry>>(ExportLogsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::plcide::LogEntry>> AsyncExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::plcide::LogEntry>>(AsyncExportLogsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::plcide::LogEntry>> PrepareAsyncExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderInterface< ::plcide::LogEntry>>(PrepareAsyncExportLogsRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void ExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest* request, ::grpc::ClientReadReactor< ::plcide::LogEntry>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderInterface< ::plcide::LogEntry>* ExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::plcide::LogEntry>* AsyncExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderInterface< ::plcide::LogEntry>* PrepareAsyncExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReader< ::plcide::LogEntry>> ExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request) {
      return std::unique_ptr< ::grpc::ClientReader< ::plcide::LogEntry>>(ExportLogsRaw(context, request));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::plcide::LogEntry>> AsyncExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::plcide::LogEntry>>(AsyncExportLogsRaw(context, request, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReader< ::plcide::LogEntry>> PrepareAsyncExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReader< ::plcide::LogEntry>>(PrepareAsyncExportLogsRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void ExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest* request, ::grpc::ClientReadReactor< ::plcide::LogEntry>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReader< ::plcide::LogEntry>* ExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request) override;
    ::grpc::ClientAsyncReader< ::plcide::LogEntry>* AsyncExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReader< ::plcide::LogEntry>* PrepareAsyncExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_ExportLogs_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status ExportLogs(::grpc::ServerContext* context, const ::plcide::LogExportRequest* request, ::grpc::ServerWriter< ::plcide::LogEntry>* writer);
  };
  template <class BaseClass>
  class WithAsyncMethod_ExportLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ExportLogs() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_ExportLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportLogs(::grpc::ServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/, ::grpc::ServerWriter< ::plcide::LogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExportLogs(::grpc::ServerContext* context, ::plcide::LogExportRequest* request, ::grpc::ServerAsyncWriter< ::plcide::LogEntry>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_ExportLogs<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_ExportLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ExportLogs() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::plcide::LogExportRequest, ::plcide::LogEntry>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::plcide::LogExportRequest* request) { return this->ExportLogs(context, request); }));
    }
    ~WithCallbackMethod_ExportLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportLogs(::grpc::ServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/, ::grpc::ServerWriter< ::plcide::LogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::plcide::LogEntry>* ExportLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_ExportLogs<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_ExportLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ExportLogs() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_ExportLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportLogs(::grpc::ServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/, ::grpc::ServerWriter< ::plcide::LogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_ExportLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ExportLogs() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_ExportLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportLogs(::grpc::ServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/, ::grpc::ServerWriter< ::plcide::LogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestExportLogs(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncWriter< ::grpc::ByteBuffer>* writer, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncServerStreaming(0, context, request, writer, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ExportLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ExportLogs() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackServerStreamingHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const::grpc::ByteBuffer* request) { return this->ExportLogs(context, request); }));
    }
    ~WithRawCallbackMethod_ExportLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ExportLogs(::grpc::ServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/, ::grpc::ServerWriter< ::plcide::LogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerWriteReactor< ::grpc::ByteBuffer>* ExportLogs(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/)  { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  template <class BaseClass>
  class WithSplitStreamingMethod_ExportLogs : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithSplitStreamingMethod_ExportLogs() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::SplitServerStreamingHandler<
          ::plcide::LogExportRequest, ::plcide::LogEntry>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerSplitStreamer<
                     ::plcide::LogExportRequest, ::plcide::LogEntry>* streamer) {
                       return this->StreamedExportLogs(context,
                         streamer);
                  }));
    }
    ~WithSplitStreamingMethod_ExportLogs() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ExportLogs(::grpc::ServerContext* /*context*/, const ::plcide::LogExportRequest* /*request*/, ::grpc::ServerWriter< ::plcide::LogEntry>* /*writer*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with split streamed
    virtual ::grpc::Status StreamedExportLogs(::grpc::ServerContext* context, ::grpc::ServerSplitStreamer< ::plcide::LogExportRequest,::plcide::LogEntry>* server_split_streamer) = 0;
  };
  typedef WithSplitStreamingMethod_ExportLogs<Service > SplitStreamedService;
  typedef WithSplitStreamingMethod_ExportLogs<Service > StreamedService;
};

}  // namespace plcide


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_plc_5fide_5fnrt_5fv1_2eproto__INCLUDED
