// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: plc_ide_nrt_v1.proto

#include "plc_ide_nrt_v1.pb.h"
#include "plc_ide_nrt_v1.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace plcide {

static const char* PLCRuntimeService_method_names[] = {
  "/plcide.PLCRuntimeService/ExportLogs",
};

std::unique_ptr< PLCRuntimeService::Stub> PLCRuntimeService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< PLCRuntimeService::Stub> stub(new PLCRuntimeService::Stub(channel, options));
  return stub;
}

PLCRuntimeService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExportLogs_(PLCRuntimeService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::plcide::LogEntry>* PLCRuntimeService::Stub::ExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::plcide::LogEntry>::Create(channel_.get(), rpcmethod_ExportLogs_, context, request);
}

void PLCRuntimeService::Stub::async::ExportLogs(::grpc::ClientContext* context, const ::plcide::LogExportRequest* request, ::grpc::ClientReadReactor< ::plcide::LogEntry>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::plcide::LogEntry>::Create(stub_->channel_.get(), stub_->rpcmethod_ExportLogs_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::plcide::LogEntry>* PLCRuntimeService::Stub::AsyncExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::plcide::LogEntry>::Create(channel_.get(), cq, rpcmethod_ExportLogs_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::plcide::LogEntry>* PLCRuntimeService::Stub::PrepareAsyncExportLogsRaw(::grpc::ClientContext* context, const ::plcide::LogExportRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::plcide::LogEntry>::Create(channel_.get(), cq, rpcmethod_ExportLogs_, context, request, false, nullptr);
}

PLCRuntimeService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      PLCRuntimeService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< PLCRuntimeService::Service, ::plcide::LogExportRequest, ::plcide::LogEntry>(
          [](PLCRuntimeService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::plcide::LogExportRequest* req,
             ::grpc::ServerWriter<::plcide::LogEntry>* writer) {
               return service->ExportLogs(ctx, req, writer);
             }, this)));
}

PLCRuntimeService::Service::~Service() {
}

::grpc::Status PLCRuntimeService::Service::ExportLogs(::grpc::ServerContext* context, const ::plcide::LogExportRequest* request, ::grpc::ServerWriter< ::plcide::LogEntry>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace plcide

